### ISSUE TITLE
[Chat] Add implementations for chat filtering

### ISSUE THREAD

**Issue by ghost** [aternosgames/odessa#1]
Things users maybe want to filter:
- [ ] Telephone numbers
- [ ] Emails
- [ ] Harassment words
- [ ] Links / Urls

Chat filters should only be interfaces and implementations of those interfaces. A chat filter MUST NOT be a event listener.

**Comment by matthi4s** [comment]
Shouldn't this be part of a different project since it is needed on every server (including lobbies) and isn't necessary for the minigame itself?

**Comment by ghost** [comment]
Outdated.
